#server:
#  port: 8081 # API GW(보통 8080)와 충돌 방지를 위한 독립 포트

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 5000
  application:
    name: order-service # [중요] MSA 환경에서 서비스 식별자(신분증) 역할

  # PostgreSQL DB 설정 (로컬 환경)
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb # 사전에 orderdb 생성 필요
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 스키마 자동 업데이트 (로컬 개발용)
    show-sql: true # 실행되는 SQL 로그 확인
    properties:
      hibernate:
        format_sql: true # SQL 가독성 향상

