server:
  port: 19094

spring:
  application:
    name: company-service

#  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

# 서비스 간 통신을 위해 DB 설정 변경
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5437/logistics_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update

      properties:
        hibernate:
          default_schema: ${DB_SCHEMA:company_schema}
          format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG

# Eureka 클라이언트
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:19090/eureka/}

## Hub 서비스 연동 포트 (19093)
#hub-service:
#  url: ${HUB_SERVICE_URL:http://localhost:19093}
