server:
  port: 19094

spring:
  application:
    name: company-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# TODO : 임시 유레카 설정. 추후 수정 요망
# Eureka Client 설정 (포트 19090)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    prefer-ip-address: true

# Hub 서비스 연동 포트 (19093)
hub-service:
  url: ${HUB_SERVICE_URL:http://localhost:19093}