dependencies {
    // Web & Validation
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // JPA & DB
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'

    // OpenFeign (서비스간 통신)
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // Eureka Client (추후 디스커버리 연동용)
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // Actuator & Tracing (Zipkin)
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'

    implementation 'org.springframework.boot:spring-boot-starter-security'
}