DROP SCHEMA IF EXISTS hub_schema CASCADE;
DROP SCHEMA IF EXISTS company_schema CASCADE;
DROP SCHEMA IF EXISTS product_schema CASCADE;
DROP SCHEMA IF EXISTS order_schema CASCADE;
DROP SCHEMA IF EXISTS delivery_schema CASCADE;
DROP SCHEMA IF EXISTS slack_schema CASCADE;
DROP SCHEMA IF EXISTS ai_schema CASCADE;
DROP SCHEMA IF EXISTS user_schema CASCADE;

CREATE SCHEMA hub_schema;
CREATE SCHEMA company_schema;
CREATE SCHEMA product_schema;
CREATE SCHEMA order_schema;
CREATE SCHEMA delivery_schema;


-- CREATE SCHEMA IF NOT EXISTS hub_schema;
-- CREATE SCHEMA IF NOT EXISTS company_schema;
-- CREATE SCHEMA IF NOT EXISTS product_schema;
-- CREATE SCHEMA IF NOT EXISTS order_schema;
-- CREATE SCHEMA IF NOT EXISTS delivery_schema;
-- CREATE SCHEMA IF NOT EXISTS slack_schema;
-- CREATE SCHEMA IF NOT EXISTS ai_schema;
-- CREATE SCHEMA IF NOT EXISTS user_schema;
