server:
  port: 19090

spring:
  application:
    name: eureka-server
  config:
    import: optional:classpath:application-secret.yaml


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/