
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.msa7'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springCloudVersion', "2025.0.3")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	// --- Spring Cloud OpenFeign 추가 ---
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
	// --- Circuit Breaker (외부 서비스 호출 장애 대응) ---
	implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
	// --- Swagger / OpenAPI ---
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14'

	//querydsl
	implementation 'io.github.openfeign.querydsl:querydsl-jpa:5.6.1:jakarta'
	annotationProcessor 'io.github.openfeign.querydsl:querydsl-apt:5.6.1:jakarta'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
